<?php

namespace CloudDoctor\Amazon;

use Aws\Ec2\Ec2Client;

class SecurityGroup
{
    /** @var string */
    private $name;
    /** @var string[] */
    private $applicableVpcIds = [];
    /** @var SecurityGroupRule[] */
    private $rulesInbound = [];
    /** @var SecurityGroupRule[] */
    private $rulesOutbound = [];

    public static function Factory() : SecurityGroup
    {
        return new SecurityGroup();
    }

    /**
     * @return string[]
     */
    public function getApplicableVpcIds(): array
    {
        return $this->applicableVpcIds;
    }

    /**
     * @param string[] $applicableVpcIds
     * @return SecurityGroup
     */
    public function setApplicableVpcIds(array $applicableVpcIds): SecurityGroup
    {
        $this->applicableVpcIds = $applicableVpcIds;
        return $this;
    }

    private function getApplicableVpc(Ec2Client $ec2Client) : ?string
    {
        $potentialVPCs = $this->getApplicableVpcIds();
        $availableVPCs = $ec2Client->describeVpcs()->get('Vpcs');
        foreach($availableVPCs as $availableVPC){
            if(in_array($availableVPC['VpcId'], $potentialVPCs)){
                return $availableVPC['VpcId'];
            }
        }
        return null;
    }

    public function assert(Request $request) : SecurityGroup
    {
        $sg = $this;
        $request->acrossRegionAction(function(string $region, Ec2Client $ec2Client) use ($sg){
            $vpcId = $this->getApplicableVpc($ec2Client);
            $exists = false;
            $allSecurityGroups = $ec2Client->describeSecurityGroups()->get('SecurityGroups');
            foreach($allSecurityGroups as $ec2SecurityGroup){
                if($ec2SecurityGroup['GroupName'] == $sg->getName()){
                    $exists = true;
                    $groupId = $ec2SecurityGroup['GroupId'];
                }
            }

            if(!$exists) {
                $makeGroupResponse = $ec2Client->createSecurityGroup([
                    'GroupName' => $sg->getName(),
                    'Description' => sprintf(
                        "Automatically generated by MEDIC at %s",
                        date("Y-m-d H:i:s")
                    ),
                    'VpcId' => $vpcId,
                ]);
                $groupId = $makeGroupResponse->get('GroupId');
            }

            $group = $ec2Client->describeSecurityGroups([
                'Filters' => [
                    [
                        'Name' => 'group-id',
                        'Values' => [$groupId],
                    ]
                ]
            ])->get('SecurityGroups')[0];

            $ipPermissions = [];

            foreach ($sg->getRulesInbound() as $inboundRule) {
                $protocols = [];

                switch($inboundRule->getProtocol()){
                    case SecurityGroupRule::PROTOCOL_ALL:
                        $protocols[] = 'tcp';
                        $protocols[] = 'udp';
                        break;
                    case SecurityGroupRule::PROTOCOL_TCP:
                        $protocols[] = 'tcp';
                        break;
                    case SecurityGroupRule::PROTOCOL_UDP:
                        $protocols[] = 'udp';
                        break;
                }

                foreach($protocols as $protocol) {
                    $ipRanges = [];
                    $groups = [];
                    #Kint::dump($inboundRule->getSource(), $group)
                    switch($inboundRule->getSource()){
                        case 'any':
                            $ipRanges[] = [
                                'Cidr' => '0.0.0.0/0',
                            ];
                            break;
                        case 'self':
                            $groups[] = [
                                'GroupId' => $group['GroupId'],
                            ];
                            break;
                        default:
                            $ipRanges[] = [
                                'Cidr' => $inboundRule->getSource(),
                            ];
                    }

                    $ipPermissions[] = array_filter([
                        'FromPort' => $inboundRule->getPort(),
                        'ToPort' => $inboundRule->getPort(),
                        'IpProtocol' => $protocol,
                        'IpRanges' => $ipRanges,
                        'Groups' => $groups,
                    ]);
                }

                $ingressRequest = array_filter([
                    'GroupId' => $group['GroupId'],
                    //'SourceSecurityGroupId' => $inboundRule->getSource() == 'self' ? $group['GroupId'] : null,
                    'IpPermissions' => $ipPermissions
                ]);
                \Kint::dump(
                    $ingressRequest
                );
                $ingressResponse = $ec2Client->authorizeSecurityGroupIngress($ingressRequest);
                \Kint::dump($ingressResponse);
            }

        });
        exit;
        return $this;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return SecurityGroup
     */
    public function setName(string $name): SecurityGroup
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return SecurityGroupRule[]
     */
    public function getRulesInbound(): array
    {
        return $this->rulesInbound;
    }

    /**
     * @param SecurityGroupRule[] $rulesInbound
     * @return SecurityGroup
     */
    public function setRulesInbound(array $rulesInbound): SecurityGroup
    {
        $this->rulesInbound = $rulesInbound;
        return $this;
    }

    /**
     * @return SecurityGroupRule[]
     */
    public function getRulesOutbound(): array
    {
        return $this->rulesOutbound;
    }

    /**
     * @param SecurityGroupRule[] $rulesOutbound
     * @return SecurityGroup
     */
    public function setRulesOutbound(array $rulesOutbound): SecurityGroup
    {
        $this->rulesOutbound = $rulesOutbound;
        return $this;
    }

    /**
     * @param SecurityGroupRule $rule
     * @return SecurityGroup
     */
    public function addRuleInbound(SecurityGroupRule $rule): SecurityGroup
    {
        $this->rulesInbound[] = $rule;
        return $this;
    }

    /**
     * @param SecurityGroupRule $rule
     * @return SecurityGroup
     */
    public function addRuleOutbound(SecurityGroupRule $rule): SecurityGroup
    {
        $this->rulesOutbound[] = $rule;
        return $this;
    }

    public function parseConfig($config) : SecurityGroup
    {
        if(isset($config['inbound'])) {
            foreach ($config['inbound'] as $inboundRule) {
                $this->addRuleInbound(
                    SecurityGroupRule::Factory($inboundRule)
                );
            }
        }

        if(isset($config['outbound'])) {
            foreach ($config['outbound'] as $outboundRule) {
                $this->addRuleOutbound(
                    SecurityGroupRule::Factory($outboundRule)
                );
            }
        }

        return $this;
    }
}